package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"reflect"
	"strings"
)

var contenidoArch = "{\n    \"Datos\": [\n        {\n            \"Indice\": \"Aa\",\n            \"Departamentos\": [\n                {\n                    \"Nombre\": \"Deportes\",\n                    \"Tiendas\": [\n                        {\n                            \"Nombre\": \"Aurora\",\n                            \"Descripcion\": \"Es una empresa multinacional estadounidense dedicada al diseño, desarrollo, fabricación y comercialización de equipamiento deportivo: balones, calzado, ropa, equipo, accesorios y otros artículos deportivos\",\n                            \"Contacto\": \"5544-3377\",\n                            \"Calificacion\": 5\n                        },\n                        {\n                            \"Nombre\": \"Amador\",\n                            \"Descripcion\": \"es una empresa alemana fabricante de accesorios, ropa y calzado deportivo, cuya sede central está en Herzogenaurach, Alemania\",\n                            \"Contacto\": \"5588-9988\",\n                            \"Calificacion\": 4\n                        },\n                        {\n                            \"Nombre\": \"Armados\",\n                            \"Descripcion\": \"Equipo extremo\",\n                            \"Contacto\": \"8995222\",\n                            \"Calificacion\": 5\n                        }\n                    ]\n                },\n                {\n                    \"Nombre\": \"Comida\",\n                    \"Tiendas\": [\n                        {\n                            \"Nombre\": \"A comer todo\",\n                            \"Descripcion\": \"todo lo que puedan pedir por un dollar\",\n                            \"Contacto\": \"559999\",\n                            \"Calificacion\": 5\n                        }\n                    ]\n                },\n                {\n                    \"Nombre\": \"celulares\",\n                    \"Tiendas\": []\n                }\n            ]\n        },\n        {\n            \"Indice\": \"B\",\n            \"Departamentos\": [\n                {\n                    \"Nombre\":\"Deportes\",\n                    \"Tiendas\": []\n                },\n                {\n                    \"Nombre\":\"Comida\",\n                    \"Tiendas\": []\n                },\n                {\n                    \"Nombre\":\"Celulares\",\n                    \"Tiendas\": [\n                        {\n                            \"Nombre\": \"Bayoneta\",\n                            \"Descripcion\": \"Telefonos militares\",\n                            \"Contacto\": \"bayoneta@gmail.com\",\n                            \"Calificacion\": 5\n                        }\n                    ]\n                }\n            ]\n        }\n    ]\n}"

type AutoGenerated struct {
	Datos []Datos `json:"Datos"`
}
type Tiendas struct {
	Nombre       string `json:"Nombre"`
	Descripcion  string `json:"Descripcion"`
	Contacto     string `json:"Contacto"`
	Calificacion int    `json:"Calificacion"`
}
type Departamentos struct {
	Nombre  string    `json:"Nombre"`
	Tiendas []Tiendas `json:"Tiendas"`
}
type Datos struct {
	Indice        string          `json:"Indice"`
	Departamentos []Departamentos `json:"Departamentos"`
}

func main() {
	/* jsonFile, err := os.Open("Categorias.json")  //abrir un archivo .json

	if err != nil{
		fmt.Println(err)
		fmt.Print("entro al if del err")
	}
	fmt.Println("archivo cargado con exito")
	defer jsonFile.Close() */

	r := strings.NewReader(contenidoArch)
	byteValue, err := ioutil.ReadAll(r)
	if err != nil{
		log.Fatal(err)
	}
	var datos AutoGenerated
	var dep []Departamentos
	json.Unmarshal(byteValue, &datos)
	fmt.Println("tipo:", reflect.TypeOf(datos))
	dep = datos.Datos[0].Departamentos
	fmt.Println(datos.Datos[0].Departamentos)
	fmt.Println(dep)
	/*for i := 0; i < len(datos.Datos); i++{
		fmt.Println("Indice: "+ datos.Datos[i].Indice)
		for j := 0; j < len(datos.Datos[i].Departamentos); j++{
			dep := datos.Datos[i].Departamentos[j]
			fmt.Println("Departamentos: ", dep)
		}
	}*/
}
