package main

import (
	"ProyectoEDD/Datos"
	"ProyectoEDD/Estructura"
	"encoding/json"
	"fmt"
	"github.com/gorilla/mux"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strconv"
)

type datoVector struct {
	listaDoble *Estructura.ListaDoble
}

type calificaciones []*Estructura.ListaDoble
var vector = calificaciones{}

type allData []*Datos.AutoGenerated
var listaDatos = allData{}

type allDep []string
var lsDep = allDep{}

type allIndex []string
var lsIndex = allIndex{}

func cargartienda(w http.ResponseWriter, r *http.Request)  {
	listaDatos = allData{}
	vector = calificaciones{}
	lsDep = allDep{}
	lsIndex = allIndex{}
	var nuevaEntrada *Datos.AutoGenerated
	reqBody, err := ioutil.ReadAll(r.Body)

	if err != nil{
		fmt.Fprintf(w, "----Error al cargar la entrada----")
	}
	json.Unmarshal(reqBody, &nuevaEntrada)
	listaDatos = append(listaDatos, nuevaEntrada)

	indices := 0
	departamentos := 0

	for _, dat := range listaDatos{
		for _, indx := range dat.Datos{
			indices += 1
			lsIndex = append(lsIndex, indx.Indice)
		}
	}
	fmt.Printf("Numerod de Indices %v \n", indices)
	for _, ind := range lsIndex{
		fmt.Println(ind)
	}
	for _, dat := range listaDatos{
		for _, indice := range dat.Datos{
			for _, depa := range indice.Departamentos {
				departamentos += 1
				lsDep = append(lsDep, depa.Nombre)
			}
			break
		}
	}
	fmt.Printf("Numero de departamentos %v \n",departamentos)
	for _, dep := range lsDep{
		fmt.Println(dep)
	}
	fmt.Println("/////////////////////")
	for _, dat := range listaDatos{
		contador := 0
		for _, auxDepa := range lsDep{
			for _, contenido := range dat.Datos {
				for _, depa := range contenido.Departamentos{
					if depa.Nombre == auxDepa{
						fmt.Println("Departamento= ", depa.Nombre)
						var lista1 = Estructura.NewListaDoble("1")
						var lista2 = Estructura.NewListaDoble("2")
						var lista3 = Estructura.NewListaDoble("3")
						var lista4 = Estructura.NewListaDoble("4")
						var lista5 = Estructura.NewListaDoble("5")
						for _, tienda := range depa.Tiendas{
							contador += 1
							fmt.Println("\t ", tienda.Nombre)
							if tienda.Calificacion == 1 {
								var t = Datos.NewTienda(tienda.Nombre, tienda.Descripcion, tienda.Contacto, tienda.Calificacion)
								Estructura.Insertar(t, lista1,contador)
							} else if tienda.Calificacion == 2 {
								var t = Datos.NewTienda(tienda.Nombre, tienda.Descripcion, tienda.Contacto, tienda.Calificacion)
								Estructura.Insertar(t, lista2,contador)
							} else if tienda.Calificacion == 3 {
								var t = Datos.NewTienda(tienda.Nombre, tienda.Descripcion, tienda.Contacto, tienda.Calificacion)
								Estructura.Insertar(t, lista3,contador)
							} else if tienda.Calificacion == 4 {
								var t = Datos.NewTienda(tienda.Nombre, tienda.Descripcion, tienda.Contacto, tienda.Calificacion)
								Estructura.Insertar(t, lista4,contador)
							} else if tienda.Calificacion == 5 {
								var t = Datos.NewTienda(tienda.Nombre, tienda.Descripcion, tienda.Contacto, tienda.Calificacion)
								Estructura.Insertar(t, lista5,contador)
							}
							fmt.Println("Lista1----------")
							Estructura.Imprimir(lista1)
							fmt.Println("Lista2---------------")
							Estructura.Imprimir(lista2)
							fmt.Println("Lista3------------------")
							Estructura.Imprimir(lista3)
							fmt.Println("Lista4---------------")
							Estructura.Imprimir(lista4)
							fmt.Println("Lista5------------------")
							Estructura.Imprimir(lista5)
						}
						vector = append(vector, lista1)
						vector = append(vector, lista2)
						vector = append(vector, lista3)
						vector = append(vector, lista4)
						vector = append(vector, lista5)
					}
				}
			}
		}
		fmt.Println("contador:", contador)
	}
	fmt.Println("///////////// Comienzo de vectores ////////////////")
	for _, vec := range vector{
		fmt.Println("vec..")
		Estructura.Imprimir(vec)
	}
	fmt.Println("Tamaño del vector",len(vector))
	generarGrafo()

	//w.Header().Set("Content-Type", "application/json")
	//w.WriteHeader(http.StatusCreated)
	//json.NewEncoder(w).Encode(nuevaEntrada)
}

func generarGrafo()  {
	err3 := os.Remove("grafo.dot")
	if err3 != nil {
		fmt.Printf("Error eliminando archivo: %v\n", err3)
	} else {
		fmt.Println("Eliminado correctamente")
	}
	path := "grafo.dot"
	acum := "digraph G {\n node [shape=record]; \n "
	nodo := ""
	nodoLista := ""
	enlace := ""
	enlaceLista := ""
	for i, vect := range vector{
		if i == 0{
			nodo += "vec" +""+ "[height=1 width="+strconv.Itoa(len(vector)*2)+" label=\"<f"+strconv.Itoa(i+1)+"> "+strconv.Itoa(i+1)+" |"
			if vect.Primero != nil{
				aux := vect.Primero
				for aux != nil {
					nodoLista += strconv.Itoa(aux.IdNodo) + "[label=\"Nombre: "+aux.Tienda.Nombre+" \\n"
					nodoLista += " Calificacion: "+strconv.Itoa(aux.Tienda.Calificacion)+"\"];\n"
					if aux.Siguiente != nil{
						enlaceLista += strconv.Itoa(aux.IdNodo)+ "->" + strconv.Itoa(aux.Siguiente.IdNodo)+";\n"
						enlaceLista += strconv.Itoa(aux.Siguiente.IdNodo)+ "->" + strconv.Itoa(aux.IdNodo)+";\n"
					}
					if aux == vect.Primero{
						enlaceLista += "vec:f"+strconv.Itoa(i+1)+" -> " + strconv.Itoa(aux.IdNodo)+";\n"
					}
					aux = aux.Siguiente
				}
			}
		}else if i > 0 && i < len(vector)-1{
			nodo += "<f"+strconv.Itoa(i+1)+"> "+strconv.Itoa(i+1)+" |"
			if vect.Primero != nil{
				aux := vect.Primero
				for aux != nil {
					nodoLista += strconv.Itoa(aux.IdNodo) + "[label=\"Nombre: "+aux.Tienda.Nombre+" \\n"
					nodoLista += " Calificacion: "+strconv.Itoa(aux.Tienda.Calificacion)+"\"];\n"
					if aux.Siguiente != nil{
						enlaceLista += strconv.Itoa(aux.IdNodo)+ "->" + strconv.Itoa(aux.Siguiente.IdNodo)+";\n"
						enlaceLista += strconv.Itoa(aux.Siguiente.IdNodo)+ "->" + strconv.Itoa(aux.IdNodo)+";\n"
					}
					if aux == vect.Primero{
						enlaceLista += "vec:f"+strconv.Itoa(i+1)+" -> " + strconv.Itoa(aux.IdNodo)+";\n"
					}
					aux = aux.Siguiente
				}
			}
		}else if i == len(vector)-1{
			nodo += "<f"+strconv.Itoa(i+1)+"> "+strconv.Itoa(i+1)+"\"];\n"
			if vect.Primero != nil{
				aux := vect.Primero
				for aux != nil {
					nodoLista += strconv.Itoa(aux.IdNodo) + "[label=\"Nombre: "+aux.Tienda.Nombre+" \\n "
					nodoLista += " Calificacion: "+strconv.Itoa(aux.Tienda.Calificacion)+"\"];"
					if aux.Siguiente != nil{
						enlaceLista += strconv.Itoa(aux.IdNodo)+ "->" + strconv.Itoa(aux.Siguiente.IdNodo)+";\n"
						enlaceLista += strconv.Itoa(aux.Siguiente.IdNodo)+ "->" + strconv.Itoa(aux.IdNodo)+";\n"
					}
					if aux == vect.Primero{
						enlaceLista += "vec:f"+strconv.Itoa(i+1)+" -> " + strconv.Itoa(aux.IdNodo)+";\n"
					}
					aux = aux.Siguiente
				}
			}
		}
	}
	acum += nodo + enlace + nodoLista + enlaceLista + "\n}\n"

	//creacion del archivo
	var _, err = os.Stat(path)
	if os.IsNotExist(err){
		var file, err = os.Create(path)
		if existeError(err) {
			return
		}
		defer file.Close()
		fmt.Println("Se ha creado un archivo")
	}

	//AHORA ESCRIBIEMOS EN EL ARCHIVO

	var file, err2 = os.OpenFile(path, os.O_RDWR, 0644)
	if existeError(err2) {
		return
	}
	defer file.Close()

	//SE ESCRIBE EN ARCHIVO
	_, err = file.WriteString(acum)
	if existeError(err) {
		return
	}

	// Salva los cambios
	err = file.Sync()
	if existeError(err) {
		return
	}

	fmt.Println("Archivo actualizado existosamente.")

	//PARTE EN DONDE GENERO EL GRAFO
	path2, _ := exec.LookPath("dot")
	cmd, _ := exec.Command(path2, "-Tpng","grafo.dot").Output()
	mode := int(0777)
	ioutil.WriteFile("grafo.png",cmd, os.FileMode(mode))
}

func existeError(err error) bool{
	if err != nil{
		fmt.Println(err.Error())
	}
	return (err != nil)
}

func main() {
	router := mux.NewRouter().StrictSlash(true)
	router.HandleFunc("/", indexRoute)
	router.HandleFunc("/cargartienda", cargartienda).Methods("POST")

	log.Fatal(http.ListenAndServe(":3000", router))

}

func indexRoute(w http.ResponseWriter, r *http.Request)  {
	fmt.Fprintf(w, "Welcome to my apisss22")
}
