package Pedidos

type AutoGenerated struct {
	Pedidos []Pedidos `json:"Pedidos"`
}
type Productos struct {
	Codigo int `json:"Codigo"`
}
type Pedidos struct {
	Fecha        string      `json:"Fecha"`
	Tienda       string      `json:"Tienda"`
	Departamento string      `json:"Departamento"`
	Calificacion int         `json:"Calificacion"`
	Productos    []Productos `json:"Productos"`
}
